bugfix: pin version of click
- problem: TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'
- solution: https://github.com/ai-dynamo/dynamo/issues/1039